name: Java CI

on: [push]

defaults:
  run:
    working-directory: java-maven
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Move package
        run: mkdir staging && cp target/*.jar staging && tree .
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: java-maven/staging